### ISSUE TITLE
Moodle 3.1 compatible

### ISSUE THREAD

**Issue by ewallah** [hrimhari/moodle-auth_emailadmin#10]
The old class constructor is deprecated in PHP7 and uses Events 1 API deprecated handlers

Possible changes:
public function __construct() {
    $this->authtype = 'emailadmin';
    $this->config = get_config('auth/emailadmin');
}

public function auth_plugin_email() {
     debugging('Use of class name as constructor is deprecated', DEBUG_DEVELOPER);
     self::__construct();
}

\core\event\user_created::create_from_userid($user->id)->trigger();

**Comment by hrimhari** [comment]
Thanks, I'll look into it toward the end of the month.

Best regards,
Felipe

**Comment by hrimhari** [comment]
Should be fixed by now.
