### ISSUE TITLE
error

### ISSUE THREAD

**Issue by manishganapathy** [hrimhari/moodle-auth_emailadmin#13]
Tried to send you an email but failed!. 
in error message
The error message 'Tried to send you an email but failed!' is most likely due to an incorrect SMTP server configuration.

**Comment by hrimhari** [comment]
I'm not sure I understand what you're saying, but the first result I get when I google 'Tried to send you an email but failed' is this: [https://moodle.org/mod/forum/discuss.php?d=268247](https://moodle.org/mod/forum/discuss.php?d=268247)
Hope that helps.
Felipe
