### ISSUE TITLE
Send welcome message to user when admin confirms through site administration

### ISSUE THREAD

**Issue by hrimhari** [hrimhari/moodle-auth_emailadmin#14]
- Externalize welcome message function.
- Move call to welcome function from confirm.php to auth.php:user_confirm()

**Comment by fredhunterccc** [comment]
Hi Felipe, I've added this code into the file [path to moodle]\lib\db\events.php but the email to the end user who has self registered is still not being sent after I confirm the account using an admin account. What else am I missing?

**Comment by hrimhari** [comment]
That's now how it works. The first bullet means there's code to be written in the plug-in that defines the class 'observer' with method 'send_confirmation'. This method would execute the logic currently sitting within confirm.php, which in turn would use that class.

The bullet about 'db/events.php' is talking about the plug-in, so it doesn't go under [moodle]/lib, it goes under [moodle]/admin/auth_emailadmin.

**Comment by fredhunterccc** [comment]
Hi Felipe, 

Please excuse me, I’m not that advanced when it comes to PHP code. I’m building my site primarily from the front end. I installed your plugin by downloading the file from the moodle plugins directory and then installing it using the built in online tool. I’m using version 1.3.0 of your addin. I’ve looked for [moodle]/admin/auth_emailadmin but can’t find it at that location on my server. 

I was just hoping that the enhancement you provided would fix my issue with the end user not receiving the account confirmation email.

**Comment by hrimhari** [comment]
The thing is that this is a planned enhancement, not something I expected people to do on their own. It's an issue tagged 'enhancement' that will be closed once it's implemented. I'm not saying you shouldn't try to do it, just that I didn't expect you to.

And my mistake, it's [moodle]/auth/emailadmin.

**Comment by fredhunterccc** [comment]
Hi Felipe,

Sorry for the misunderstanding, I will wait for the next release. As I said I’m a complete novice. Both to Moodle and Github. It’s just that I thought that the function to send a confirmation to the user who has registered was already supposed to be there. My issue is that it isn’t working. I’ve confirmed that the email account I’m using the test the self-registration isn’t blocking the noreply@xxxxxx address I’ve set up on my moodle instance as other types of emails are going through. Any help you can give me to fix this would be appreciated. I really like your plugin and it I the most suitable to what I need to accomplish for my site.

Regards,

Fred Hunter
Systems Improvement Officer
Tel: 024 7678 5467

Corporate Users: Log your incident or service request on MyServiceDesk – no need to email or ring us

Do you have a “how do I…” IT related question? Take a look at our Ask About IT community forum

**Comment by hrimhari** [comment]
Hi Fred,

The feature has been released.

If you still have problems, you should [diagnose sending emails from Moodle or PHP](http://lmgtfy.com/?q=moodle+cannot+send+email). 

The plug-in delegates the sending to Moodle/PHP and has no control on how the message is delivered afterwards.

Best regards,
Felipe

**Comment by fredhunterccc** [comment]
Hi Felipe,

Will I be able to automatically get the update from my noodle front end plugin manager or do I have to use another procedure to update it?

Also, I feel its important to reiterate the the initial email to the administrator (when a new user self registers) is going through as expected, also when a user requests a password reset, they get an email. This means that the email settings in my noodle instance are functioning correctly. the  only email which is not being triggered is the one the user is supposed to receive when an admin confirms their account. Will your feature update resolve this?

Tha ks

Fred

________________________________

**Comment by fredhunterccc** [comment]
All working now since the update. Thanks for a quick turnaround!

Fred Hunter
Systems Improvement Officer
Tel: 024 7678 5467

Corporate Users: Log your incident or service request on MyServiceDesk – no need to email or ring us

Do you have a “how do I…” IT related question? Take a look at our Ask About IT community forum
