### ISSUE TITLE
Change proposal: Which users appear in the notification strategy option

### ISSUE THREAD

**Issue by henriquefm** [hrimhari/moodle-auth_emailadmin#18]
Hello,

I am probably going to have to make this change, so I can make a PR if you like it. Currently, only the site admins appear in the "Notification strategy" option. But the admins are not the only ones that can confirm a user, any user with the "moodle/user:update" capability can. In a default Moodle instance, for example, Managers have that capability. So I believe it makes more sense to have anyone with that capability appearing in the "Notification strategy" and with the possibility to choose more than one user, kinda like in the /admin/settings.php?section=courserequest page. 
Thanks!

**Comment by hrimhari** [comment]
Been a long time. I'll take a look into replacing the admin list by a list of users with that capability.
