### ISSUE TITLE
Update compatible Moodle version numbers

### ISSUE THREAD

**Issue by michael-milette** [hrimhari/moodle-auth_emailadmin#20]
Thank you for making this useful plugin available to the global Moodle community.

At the top of the https://moodle.org/plugins/auth_emailadmin page, it still says that the plugin is only compatible with Moodle 2.9 and 3.0 even through, on the version page, it says that it is compatible with Moodle 3.1, 3.2, 3.3 and 3.4. Any chance that you could correct this small confusion Moodle.org? :-)

Best regards,

Michael Milette

**Comment by hrimhari** [comment]
Can't find the issue. Maybe already fixed?
