### ISSUE TITLE
profil field not visible

### ISSUE THREAD

**Issue by henrypatz** [hrimhari/moodle-auth_emailadmin#23]
We just updated to moodle 3.5.1+ The auth_emailadmin works.
BUT: It does not work with (extra) profilfields as we used for ages to specify the class/group, where new users are to registrate. The selfregistration shows the categorie for the (in our case dropdown) additional user-profilfield. The field is not there... And: Because it was a needed field, the registration failed without a visible error...
Henry

**Comment by optical65** [comment]
I confirm the error in the plugin with the moodle 3.5.1 vid is visible the category but not the fields
Francesco

**Comment by hrimhari** [comment]
Hi, I can see profile fields on my side. I'll close the issue. Let me know if you still have this problem so we can investigate it further.
