### ISSUE TITLE
DateTime not converted

### ISSUE THREAD

**Issue by SVIeSolutions** [hrimhari/moodle-auth_emailadmin#25]
Hi, I added custom fields to the user profile, one is the birth date. 
But in the mail, the date is displayed in unix time (example: 702792000), which is not very useful ;)
Would it be possible to validate the type and convert the date value to something readable...
Thanking you in advance!

**Comment by hrimhari** [comment]
The fix will use better formatting. But when the profile field is a checkbox, it will cause some minor formatting issues with the message.
