### ISSUE TITLE
UTF-8 charset

### ISSUE THREAD

**Issue by DavidDelco** [hrimhari/moodle-auth_emailadmin#31]
As requested "As for Unicode characters, I'll have to try it out. Please open an issue in Github."
I would like to point out a small problem that I experienced with this wonderful plugin.
I have translated mail messages into Italian and I use characters with accents, but in reality I am not able to see those characters, which are replaced with symbols.

Thank you for help.
David

**Comment by hrimhari** [comment]
Hi David,

I installed Moodle's language pack for Italian and created fake translated messages for the plug-in using the Language customization interface within my Moodle. I added some unicode characters to all messages, such as mão, ué, à, e até ❤️

All characters displayed correctly, both in Moodle and in the email messages I received.

You may have a problem with your setup. Maybe your email settings are not correct? Check out this in your Moodle: Site Administration --> Server --> Email --> Outgoing Configuration --> Email display settings --> Character set: must be UTF-8.

I'm closing the issue.

Best regards,
Felipe
