### ISSUE TITLE
Version 1.4.4 incompatible with Moodle 3.3

### ISSUE THREAD

**Issue by effgarces** [hrimhari/moodle-auth_emailadmin#32]
The function profile_get_user_fields_with_data() only showed up with moodle 3.4, from what I able to gather, thus version 1.4.4 does not work properly with Moodle 3.3, unfortunately the version I'm currently stuck with. Upon registration the user is greated with a blank screen, changing the function list_custom_fields to the previous version seems to solve the issue.

**Comment by hrimhari** [comment]
I'll trust you on that. But your alternative for now is to use an older version that doesn't refer to this api...

**Comment by hrimhari** [comment]
My solution will be to remove versions prior to 3.4 from the compatibility list and require 3.4 as a minimum.

**Comment by effgarces** [comment]
My solution was to copy the code for the function list_custom_fields, that uses the  profile_get_user_fields_with_data function, from the previous version, and it seems to be working well so far.
Yes that's the most sensible solution for this problem. I was just letting people know that there was this issue to this combination of versions, hopefully I was the only one that was affect by it.

**Comment by hrimhari** [comment]
Removed 3.3 from compatibility list.
