### ISSUE TITLE
Compatibility with moodle 3.9

### ISSUE THREAD

**Issue by ncatusse** [hrimhari/moodle-auth_emailadmin#37]
Hello,

The 1.4.4 version of the plugin is not compatible with moodle 3.9.
The functions upgrade_fix_config_auth_plugin_names() and upgrade_fix_config_auth_plugin_defaults() called in the file db/upgrade.php have been removed in version 3.9 of moodle (see https://github.com/moodle/moodle/blob/master/auth/upgrade.txt).

Thank you for your work!

**Comment by hrimhari** [comment]
Thank you for pointing that out. I'll address it asap.
