### ISSUE TITLE
Administrators should receive the configuration email in their own language.

### ISSUE THREAD

**Issue by ewallah** [hrimhari/moodle-auth_emailadmin#4]
The registration emails sent by the plugin to the administrator, are in the language of the new registrant. As long as an admin is a little bit multilingual, there is no problem. But it cannot be that the messages are puzzles where he has to deduct if he has to read from right to left, or from left to right. These messages should be sent in the (poor) language the administrator masters.

**Comment by hrimhari** [comment]
Another work around if you have admins with different mother tongues would be to add all relevant languages to one single admin message text and have it replicated to all relevant languages.

**Comment by ewallah** [comment]
Hello Felipe,

one thing we know for sure, is that the administrator(s) understand the system language ($CFG->lang). If he/she was able to install the plugin, we can assume that this language is not a problem:wink:. So a function like:

    $txt = get_string_manager()->get_string('auth_emailadminconfirmation', 'auth_emailadmin', null, $CFG->lang);

collects strings that should be understood.

**Comment by hrimhari** [comment]
Too easy... I had to do something much crazier. It's on a branch until I can
actually test it. We'll see...

**Comment by hrimhari** [comment]
Delivered
