### ISSUE TITLE
People cannot log in those who created the account used self registration used admin approval option when this authentication option disabled

### ISSUE THREAD

**Issue by jasimp** [hrimhari/moodle-auth_emailadmin#47]
Hi 
I just disable self registration used admin approval option due to some security investigation.
But now the user cannot log in those who create the account using this self registration used admin approval option 
is this a bug or its programmed such way?

**Comment by hrimhari** [comment]
This is normal moodle behavior.

**Comment by jasimp** [comment]
Thanks Mr. Felipe
Just to confirm
