### ISSUE TITLE
How to validate user email 

### ISSUE THREAD

**Issue by jasimp** [hrimhari/moodle-auth_emailadmin#48]
With this admin approval plug in , two issues are there

1. The user not getting any email notification while registering used this authentication option. so any one can create an account for others
2. Also the user not getting any account validation email to validate their email address as the admin getting the link. So there is chance for spelling error while creating the account and this can cause spam later
How to solve this two issues

The admin approval link need to be generated after the user email validated.

**Comment by hrimhari** [comment]
Spam is controlled through Captcha.

**Comment by jasimp** [comment]
Sorry, i think you misunderstand my poor language
The spaming which  i means the email delivery issue due to bad reputation

if a user type the email id wrongly and the admin approved it with out validating the email id of the user, then the system will send in valid email to the wrong registered email ID and this kind of huge errors will lead to the email and IP reputation issue

Do you think the current scenario is good?
