### ISSUE TITLE
Original email plugin login page instructions not included

### ISSUE THREAD

**Issue by alexlegg1992** [hrimhari/moodle-auth_emailadmin#7]
I had trouble trying to get the original login page instructions to appear. The: 
"For full access to courses you'll need to take a minute to create a new account for yourself on this web site. Each of the individual courses may also self-enrolment. Here are the steps:
Fill out the New Account form with your details." etc. etc. etc.

I managed to solve it...

If you go to moodle/login/index_form.html...

Search for "loginsteps" and change the line underneath from: ($CFG->registerauth == 'email') to ($CFG->registerauth == 'emailadmin')

Hope this helps,

Alex

**Comment by hrimhari** [comment]
Hey Alex, thanks for the heads up. There was a similar issue regarding
enabling/disabling CAPTCHA. Looks like I'll have to add some notes about that.
 
Best regards,
Felipe
