### ISSUE TITLE
Moodle 2.9 compatibility

### ISSUE THREAD

**Issue by alexlegg1992** [hrimhari/moodle-auth_emailadmin#8]
Hi Felipe,

Hope all is well.

Do you know if this plugin will work with Moodle 2.9 as I'm looking to upgrade my instance.

If not, is there any plan on upgrading the plugin? and if no would this best easy to do?

Many thanks,

Alex

**Comment by hrimhari** [comment]
As a general rule, the plugin is safe from its current version onward.

Let me know if you have any problems with version 2.9.

Also let me know if you don't :)

Best regards,
Felipe

**Comment by alexlegg1992** [comment]
Hi Felipe,

I've tested the plugin on a cloned test version of our live site and it doesn't appear to work. 

The site admin doesn't receive the registration email.

SMTP Email settings are all correct.

Email-based self-registration with admin confirmation Authentication is enabled and set as the type of Self registration.

I can't think of what could be causing the problem, any ideas? 

Kinda hoping the solution is something really silly :D 

Many thanks,

**Comment by hrimhari** [comment]
Hi Alex,
 
Can you send me:
 
1- Some screen shots of your setup including:
1.1- the page with the plugin selected as authentication method
1.2- the page that shows the admin's email address
 
2- How many users with admin role you have (note that only the first will
receive notifications)
 
3- The step-by-step of how you attempted to test it, since user registration up
to confirmation (if you got that far)
 
Thank you,
Felipe

**Comment by alexlegg1992** [comment]
1.1:
![1](https://cloud.githubusercontent.com/assets/7630555/8409982/4d9dc1bc-1e73-11e5-8b9b-2d1c8c419b3c.png)
![2](https://cloud.githubusercontent.com/assets/7630555/8409983/5104f636-1e73-11e5-815a-b78da682b616.png)
![3](https://cloud.githubusercontent.com/assets/7630555/8409984/53001510-1e73-11e5-970b-a966fb036bb7.png)
![4](https://cloud.githubusercontent.com/assets/7630555/8409986/56aaf752-1e73-11e5-9eb7-8ceb6341a150.png)

1.2 / 2:
![5](https://cloud.githubusercontent.com/assets/7630555/8409993/63868c66-1e73-11e5-95d9-8d41a3da960a.png)

3:
I created a new account under "Is this your first time here?" and filled out the information. And the site admin hasn't received the registration email.

I re-applied the SMTP settings at Site admin > Plugins > Message outputs > Email. These are working settings that are currently running on 5+ websites.
I removed the site administrator and added it again.
